In [1]:
import numpy as np


In [7]:
# basic objects
A = np.array([[1,0.3],[0.1, 1.3]], dtype=np.float32)
print(A)

B = np.array([[3,4],[1,2]], dtype=np.float32)
print(B)

print(A+B)


[[1.  0.3]
 [0.1 1.3]]
[[3. 4.]
 [1. 2.]]
[[4.  4.3]
 [1.1 3.3]]


In [9]:
print(np.sum(A*B))
print(np.dot(A,B))

6.8999996
[[3.3       4.6      ]
 [1.5999999 3.       ]]


In [10]:
#matrix multiplication
def mul_matrix(x, y):
    c = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            c[i,j] = np.dot(x[i,:], y[:,j])
    return c


In [11]:
print(mul_matrix(A,B))

[[3.29999995 4.5999999 ]
 [1.5999999  3.        ]]


In [12]:
# transpose matrix

print(A)
print(A.transpose())

[[1.  0.3]
 [0.1 1.3]]
[[1.  0.1]
 [0.3 1.3]]


In [13]:
print(A*B)
print(A.dot(B))

[[3.  1.2]
 [0.1 2.6]]
[[3.3       4.6      ]
 [1.5999999 3.       ]]


In [14]:
a = np.array([[1,2],[2,3]])
b = np.array([[2,2],[3,4]])

print(a)
print(b)

print(a*b)
print(a.dot(b))

[[1 2]
 [2 3]]
[[2 2]
 [3 4]]
[[ 2  4]
 [ 6 12]]
[[ 8 10]
 [13 16]]


In [15]:
#inverses
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
print(np.linalg.inv(A))

[[ 1.023622   -0.2362205 ]
 [-0.07874016  0.7874016 ]]


In [18]:
print(A.dot(np.linalg.inv(A)))

[[1. 0.]
 [0. 1.]]


In [19]:
print(np.linalg.inv(A).dot(A))

[[1. 0.]
 [0. 1.]]


In [20]:
try:
    bad_matrix=np.array([[1,2],[2,4]])
    print(bad_matrix)
    print(np.linalg.inv(bad_matrix))
except Exception as e:
    print(e)

[[1 2]
 [2 4]]
Singular matrix


In [21]:
value = list(range(-5,6))
print(value)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]


In [22]:
x,y = np.meshgrid(value,value)

In [23]:
print(x)

[[-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]]
